pin_run_as_build:
  python:
    min_pin: x.x
    max_pin: x.x
  r-base:
    min_pin: x.x
    max_pin: x.x
  libboost:
    max_pin: x.x.x
ignore_build_only_deps:
- python
- numpy
extend_keys:
- ignore_version
- pin_run_as_build
- ignore_build_only_deps
- extend_keys
gnu:
- 2.12.2
openjpeg:
- '2.3'
python_impl:
- cpython
python_implementation:
- cpython
serf:
- 1.3.9
lua:
- '5'
apr:
- 1.6.3
boost_cpp:
- '1.73'
qtwebkit:
- 'true'
glib:
- '2'
numpy:
- '1.20'
MACOSX_DEPLOYMENT_TARGET:
- '10.9'
blas_impl:
- mkl
libnetcdf:
- '4.6'
sqlite:
- '3'
cross_compiler_target_platform:
- win-64
- win-32
openblas:
- 0.3.3
VERBOSE_CM:
- VERBOSE=1
giflib:
- '5'
channel_targets:
- defaults
macos_machine:
- x86_64-apple-darwin13.4.0
icu:
- '58'
rust_compiler_version:
- 1.46.0
gmp:
- '6.1'
hdf5:
- 1.10.6
xz:
- '5'
macos_min_version:
- '10.9'
fortran_compiler:
- intel-fortran
libwebp:
- 1.0.0
perl:
- '5.26'
libxml2:
- '2.9'
cran_mirror:
- https://mran.microsoft.com/snapshot/2018-01-01
cairo:
- '1.14'
dbus:
- '1'
lzo:
- '2'
zlib:
- '1.2'
libdap4:
- '3.19'
libtiff:
- '4.1'
g2clib:
- '1.6'
mpfr:
- '4'
m2w64_fortran_compiler:
- m2w64-toolchain
m2w64_c_compiler:
- m2w64-toolchain
hdfeos5:
- '5.1'
boost:
- '1.73'
libpng:
- '1.6'
clang_variant:
- clang
VERBOSE_AT:
- V=1
libxslt:
- '1.1'
mkl:
- '2021'
tk:
- '8.6'
gstreamer:
- '1.14'
cpu_optimization_target:
- nocona
libgd:
- 2.2.5
hdfeos2:
- '2.20'
libkml:
- '1.3'
fontconfig:
- '2.13'
proj:
- 6.2.1
libgsasl:
- '1.8'
openssl:
- 1.1.1
hdf4:
- '4.2'
r_implementation:
- mro-base
- r-base
m2w64_cxx_compiler:
- m2w64-toolchain
libffi:
- 3.2.1
libprotobuf:
- 3.11.2
r_version:
- 3.5.0
llvm_variant:
- llvm
bzip2:
- '1.0'
freetype:
- '2.10'
libgdal:
- '3.0'
r_base:
- '3.5'
proj4:
- 5.2.0
target_platform:
- win-64
gst_plugins_base:
- '1.14'
noarch_python:
- python
cyrus_sasl:
- 2.1.26
pixman:
- '0.30'
rust_compiler:
- rust
- rust-gnu
jpeg:
- '9'
expat:
- '2.2'
harfbuzz:
- '2.4'
readline:
- '8.0'
cxx_compiler:
- vs2017
vc:
- '14'
geos:
- 3.8.0
c_compiler:
- vs2017
python:
- '3.8'
fortran_compiler_version:
- 2019.0.0
zip_keys:
- - vc
  - c_compiler
  - cxx_compiler
  - fortran_compiler_version
  - python
  - geos
